### ISSUE TITLE
Поправить алгоритм

### ISSUE THREAD

**Issue by Kasiwadzaki** [rizomus/TestTaskUnoSoft#1]
Добрый день, меня зовут Вадим, я разработчик компании Uno-Soft.

В тестовом задании есть пункт в котором указано что по результату работы программы должен создаваться файл с результатом, про вывод в консоль ничего не было. Из-за вывода в консоль вы не укладываетесь в итоговое время 30 секунд, прошу поправить этот момент.

**Comment by rizomus** [comment]
День добрый! Исправил.
